### ISSUE TITLE
How to add Tag?

### ISSUE THREAD

**Issue by zilongshanren** [yoshinari-nomura/org-octopress#20]
On default, it only supports Category.

**Comment by yoshinari-nomura** [comment]
Currently, we have no way to add tags in the YAML front matter.

As you know, org-mode has its own tag mechanism, which can be added node-by-node basis.
On the other hand, Jekyll's tag is file-by-file basis.
I don't have good idea how to embed the Jekyll's tag names into org-file.

**Comment by zilongshanren** [comment]
@yoshinari-nomura 
Why can't we have YAML format to add tags? When writing in markdown , it is possible to add tags.
Any particular reasons?
Thanks.

**Comment by yoshinari-nomura** [comment]
Sorry, I have misunderstood,

Do you mean you need `#+JEKYLL_TAGS` like `#+JEKYLL_CATEGORIES`?
I have pushed that idea to the experimental branch `support-tags`.
Does it work for you?

**Comment by zilongshanren** [comment]
@yoshinari-nomura  I will try it, thanks.

**Comment by zilongshanren** [comment]
Thanks @yoshinari-nomura 
It works, but not perfect. 
If I add two or more keywords, I must add a '-' prefix before each of the tags.

**Comment by zilongshanren** [comment]
@yoshinari-nomura  
I have modified  `org-jekyll--yaml-front-matter` to 

```
(defun org-jekyll--yaml-front-matter (info)
  (let ((title
         (org-jekyll--get-option info :title))
        (date
         (org-jekyll--get-option info :date))
        (layout
         (org-jekyll--get-option info :jekyll-layout org-jekyll-layout))
        (categories
         (org-jekyll--get-option info :jekyll-categories org-jekyll-categories))
        (tags
         (org-jekyll--get-option info :jekyll-tags org-jekyll-tags))
        (published
         (org-jekyll--get-option info :jekyll-published org-jekyll-published))
        (comments
         (org-jekyll--get-option info :jekyll-comments)))
    (unless (equal published "true")
      (setq title (concat "[PREVIEW] " title)))
    (concat
     "---"
     "\ntitle: \""    title
     "\"\ndate: "     date
     "\nlayout: "     layout
     "\ncategories: " categories
     "\ntags: "       (mapconcat #'(lambda (text)
                                     (concat "\n- " text)) (split-string tags) " ")
     "\npublished: "  published
     "\ncomments: "   comments
     "\n---\n")))
```

The trick is 

```
(mapconcat #'(lambda (text)
                                     (concat "\n- " text)) (split-string tags) " ")
```

Now it meet my needs now.
Thanks.

**Comment by zilongshanren** [comment]
@yoshinari-nomura  Could this be merged back to master branch?

**Comment by yoshinari-nomura** [comment]
@zilongshanren , thanks.

I've only pushed my original `support-tags` to master for now.

According to the page about YAML front matter  http://jekyllrb.com/docs/frontmatter/ :
> tags:  Similar to categories, one or multiple tags can be added to a post. 
> Also like categories, tags can be specified as a YAML list or a space-separated string. 

It seems to be a fault in Jekyll (father of Octopress) itself, not in our emacs-lisp.

Your hack works fine, but thinking straight, you should write YAML list by adding `-` to each element in the right YAML fomat. Or send an issue to Jekyll or Octopress guys asking for tags works same as categories.

What do you say?

**Comment by zilongshanren** [comment]
@yoshinari-nomura  I will try to send an issue to Octopress, but now, the tags support is not perfect.
Before the issue could be resolve by the Jekyll guys, I think you should mention it in the README.

**Comment by zilongshanren** [comment]
@yoshinari-nomura 
 Because Jekyll is really really slow when blog post exceed 50+. So I have switched to  https://github.com/hexojs/hexo   It is a Node.js based static blog solution.

 And the good thing is that I can migrate my Octopress blog to hexo easily.  Hexo also keeps back compatibility with Octopress. And the tag support is the same as Octopress.

So at this point, I would suggest you to accept my hacking. or at least we should support multiple tags with space separated.

Thanks.

**Comment by yoshinari-nomura** [comment]
OK, I'm willing to merge your code.
Do you mind sending me a new PR on the top of current master?

Thaks in advance.

**Comment by zilongshanren** [comment]
@yoshinari-nomura  
Sure, I will create a PR later.
Thanks :+1:

**Comment by zilongshanren** [comment]
@yoshinari-nomura 
Here is the PR:
https://github.com/yoshinari-nomura/org-octopress/pull/22

**Comment by yoshinari-nomura** [comment]
Thanks. I've merged your PR.
