### ISSUE TITLE
How to add Excerpts in org mode?

### ISSUE THREAD

**Issue by sj20082663** [yoshinari-nomura/org-octopress#21]
The default macro {{{more}}} seems not work for me. I got a error  "org-macro-replace-all: 
Undefined Org macro: more; aborting". So how could I add a excerpt in my org mode.
                                                                    Thank you.

**Comment by sj20082663** [comment]
I finally find it in the sample setupfile which has a custom MACRO more. Sorry for bother and close this.

**Comment by yoshinari-nomura** [comment]
Sorry for my snail response from my cellphone.
I'm in the summer (Obon) vacation and off my terminal.
I hope you enjoy your summer and write a blog with org-octopress.
